apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-whook-secret
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    {{- include "pr-preview-bind.labels" . | nindent 4 }}
stringData:
  secret: {{ .Release.Name }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-git-cred
  annotations:
    tekton.dev/git-0: https://github.com
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    {{- include "pr-preview-bind.labels" . | nindent 4 }}
type: Opaque
stringData: 
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://{{ .Values.GithubUsername }}:{{ .Values.GithubReadToken }}@github.com
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-prp-info
  labels: 
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    {{- include "pr-preview-bind.labels" . | nindent 4 }}
    epinio.io/configuration: "true"
    epinio.io/configuration-origin: {{ .Values.epinio.serviceName }}
    epinio.io/configuration-type: service
type: Opaque
stringData:
  {{- if .Values.GithubOrganization }}
  githubOrganization: {{ .Values.GithubOrganization }}
  {{- else }}
  githubOrganization: {{ .Values.GithubUsername }}
  {{- end }}
  githubUserName: {{ .Values.GithubUsername }}
  githubWebhookToken: {{ .Values.GithubWebhookToken }}
  slackWebhookURL: {{ .Values.SlackWebhookURL }}