apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-xs
  annotations:
    external-dns.alpha.kubernetes.io/target: lb-01.stackio-beta.mtl02.stack.io
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: "{{ .Release.Name }}-auth"
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    {{- include "xs-server.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Release.Name }}.platform.beta.sidepro.app
    http:
      paths:
      - backend:
          service:
            name: {{ include "xs-server.fullname" . }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Release.Name }}.platform.beta.sidepro.app
    secretName: {{ .Release.Name }}-xs-tls
