{{- $username := include "xs-server.randomUsername" . }}
{{- $password := include "xs-server.randomPassword" . }}

apiVersion: v1
kind: Secret
stringData:
  username: {{ $username | quote }}
  password: {{ $password | quote }}
  host: {{ .Release.Name }}.platform.beta.sidepro.app
type: Opaque
metadata:
  name: {{ .Release.Name }}
  annotations:
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    meta.helm.sh/release-name: {{ .Release.name }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    epinio.io/configuration: "true"
    epinio.io/configuration-origin: {{ .Values.epinio.serviceName }}
    epinio.io/configuration-type: service
---
apiVersion: v1
kind: Secret
data: 
  auth: {{ htpasswd $username $password | b64enc | quote }}
type: Opaque
metadata:
  name: {{ .Release.Name }}-auth
  annotations:
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    meta.helm.sh/release-name: {{ .Release.name }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    epinio.io/configuration: "false"