apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "data-{{ include "apm.fullname" . }}-jaeger"
  labels:
    {{- include "apm.labels" . | nindent 4 }}
    {{- include "apm.epinioLabels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
