apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    {{- include "cicd-bind.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-pipeline-cicd
spec:
  description: |
    This pipeline clones a git repo, then echoes the README file to the stdout.
    
  params:
    - description: The git repo URL to clone from.
      name: repo-url
      type: string
    - description: git revision
      name: git-revision
      type: string
    - description: The git branch name
      name: git-branch
      type: string
    - description: application name on epinio
      name: app-name
      type: string
  tasks:
  {{- if and .Values.SlackWebhookURL (ne .Values.SlackWebhookURL "") }}
    - name: start-feedback
      taskRef:
        kind: Task
        name: slack-{{ .Release.Name }}-cicd
      params:
        - name: GitHubInfoSecretName
          value: "{{ .Release.Name }}-push-info-cicd"
        - name: Message
          value: "The ci-cd pipeline is starting for #$(params.app-name)!"
  {{- end }}
    - name: fetch-source
      {{- if and .Values.SlackWebhookURL (ne .Values.SlackWebhookURL "") }}
      runAfter:
        - start-feedback
      {{- end }}
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
        - name: basic-auth
          workspace: git-credentials  
    - name: epinio-push
      runAfter:
        - fetch-source
      taskRef:
        kind: Task
        name: {{ .Release.Name }}-epinio-push-cicd
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: app-name
          value: $(params.app-name)
{{- if and .Values.SlackWebhookURL (ne .Values.SlackWebhookURL "") }}
  finally:
    - name: end-feedback
      taskRef:
        kind: Task
        name: slack-{{ .Release.Name }}-cicd
      params:
        - name: GitHubInfoSecretName
          value: "{{ .Release.Name }}-push-info-cicd"
        - name: Message
          value: |
            🚀 CI/CD process completed for *$(params.app-name)*!
            
            📊 Summary:
            • App: $(params.app-name)
            • Git revision: `$(params.git-revision)`
            • Branch: $(params.git-branch)
            • Push status: $(tasks.epinio-push.status)

            📋 View build logs:
            • CLI: `sidepro app logs --build $(params.app-name)`
            • GUI: Select “Last Build Logs” from the ellipses menu under “Applications”
{{- end }}
  workspaces:
    - description: |
        This workspace contains the cloned repo files, so they can be read by the next task.
      name: shared-data
    - description: My git credentials
      name: git-credentials
