ingress:
  class: nginx
  domain: domain.tld
  annotations: {}
keycloak:
  host: my.keycloak.com
  realm: my-realm
  clientId: my-client-id
  clientSecret: my-client-secret
  # generate cookie token:
  # docker run -ti --rm python:3-alpine \
  # python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
  cookieSecret: my-cookie-secret
epinio: {}
