{{- if .Values.ingress.enabled -}}
{{- $fullName := include "canary-checker.name" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "canary-checker.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/target: lb-01.stackio-beta.mtl02.stack.io
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ printf "%s.%s" .Release.Name . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ printf "%s.%s" .Release.Name .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 8080
{{- end }}
