apiVersion: v1
kind: Service
metadata:
  name: {{ include "canary-checker.name" . }}
  labels:
    {{- include "canary-checker.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "canary-checker.selectorLabels" . | nindent 4 }}
