{{- if .Values.userConfig.basicAuthHtpasswd }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "epinio-truncate" .Values.epinio.appName }}-auth"
  labels:
    {{- include "epinio-application.labels" . | nindent 4 }}
  annotations:
    {{- include "epinio-application.annotations" . | nindent 4 }}
type: Opaque
data:
  auth: {{ .Values.userConfig.basicAuthHtpasswd | b64enc }}
{{- end }}
