{{- range .Values.epinio.routes }}
{{- if not .secret }}
---
# apiVersion: "cert-manager.io/v1"
# kind: Certificate
# metadata:
#   name: {{ include "epinio-truncate" (print $.Values.epinio.appName "-" .id) }}
#   labels:
#     {{- include "epinio-application.labels" $ | nindent 4 }}
#   annotations:
#     {{- include "epinio-application.annotations" $ | nindent 4 }}
# spec:
#   secretName: {{ include "epinio-truncate" (print $.Values.epinio.appName "-" .id "-tls") }}
#   dnsNames:
#   - {{ .domain | quote }}
#   issuerRef:
#     name : {{ $.Values.epinio.tlsIssuer | quote }}
#     kind: ClusterIssuer
# {{- end }}
---
{{ $ingressConfig := $.Values.chartConfig.ingress | fromYaml }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "epinio-truncate" (print $.Values.epinio.appName "-" .id) }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    blackbox.io/enabled: "true"
    blackbox.io/path: {{ default "/" $.Values.userConfig.monitoringPath | quote }}
    {{- range $key, $value := $ingressConfig.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- include "epinio-application.annotations" $ | nindent 4 }}
    {{- if $.Values.userConfig.basicAuth }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: "{{ include "epinio-truncate" $.Values.epinio.appName }}-auth"
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    {{- end}}
  labels:
    {{- include "epinio-application.labels" $ | nindent 4 }}
spec:
  {{- with $.Values.epinio.ingress }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  rules:
    - host: {{ .domain | quote }}
      http:
        paths:
          - backend:
              service:
                {{- if $.Values.userConfig.enableScaleToZero }}
                name: "{{ include "epinio-truncate" $.Values.epinio.appName }}-proxy"
                {{- else }}
                name: {{ include "epinio-truncate" $.Values.epinio.appName }}
                {{- end }}
                port:
                  number: 8080
            path: {{ .path | quote }}
            pathType: ImplementationSpecific
#   tls:
#     - hosts:
#       - {{ .domain | quote }}
# {{- if .secret }}
#       secretName: {{ .secret | quote }}
# {{- else }}
#       secretName: {{ include "epinio-truncate" (print $.Values.epinio.appName "-" .id "-tls") }}
# {{- end }}
{{- end }}
