apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "epinio-truncate" .Values.epinio.appName }}
spec:
  podSelector:
    matchLabels:
    {{- include "epinio-application.labels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: keda
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
