{{- range .Values.epinio.configurations }}
{{- if (hasSuffix "-prp-info" .) }}
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: {{ $.Release.Name }}-cr-whook
  labels:
    {{- range $key, $value := $.Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    app.kubernetes.io/managed-by: epinio
    app.kubernetes.io/part-of: {{ $.Release.Namespace | quote }}
    app.kubernetes.io/name: {{ $.Values.epinio.appName | quote }}
    app.kubernetes.io/component: application
spec:
  taskRef:
    name: create-webhook-{{ trimSuffix "-prp-info" . }}
  params:
  - name: GitHubRepo
    value: {{ $.Values.epinio.appName }}
  - name: GitHubInfoSecretName
    value: {{ . }}
  - name: ExternalDomain
    value: {{ trimSuffix "-prp-info" . }}.epinio.beta.stack.io
  timeout: 1000s
  serviceAccountName: {{ trimSuffix "-prp-info" . }}-createwebhook
---
{{- end }}
{{- end }}